# Generated by Django 5.0.5 on 2024-10-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
