# Generated by Django 5.0.5 on 2024-11-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
    ]
